name: Build on Tag

on:
  workflow_call:
  workflow_dispatch:
env:
  PYTHON_VERSION: "2"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3
        path: zipper

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: Dark-Ages
      with:
        arch: arm64
        compiler: proton-clang/master
        defconfig: vendor/a42xq_eur_open_defconfig
        image: Image.gz
        dtb: false
        dtbo: false
        kernelsu: true
        kprobes: false

    - name: Release build
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.build.outputs.outfile }}
        token: ${{ secrets.GITHUB_TOKEN }}
